# Change these first
owner: Dom-Store # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Server
    url: $SECRET_SERVER

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.exitnetwork.dev
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Dom Store
  introTitle: "**Uptime** Dom Store."
  introMessage: Status dos nossos serviços.
  navbar:
    - title: Status
      href: /
    - title: Discord
      href: https://discord.gg/tBsK5QbpgG

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
